In [1]:
import pandas as pd

In [2]:
def loadPricesAsDF(fn):
    global nt, nInst
    #df=pd.read_csv(fn, sep='\s+', names=cols, header=None, index_col=0)
    df=pd.read_csv(fn, sep='\s+', header=None, index_col=None)
    nt, nInst = df.values.shape
    return df

pricesFile="../prices.txt"
prcAll = loadPricesAsDF(pricesFile)

In [4]:
prcAll

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,60.17,10.11,40.89,33.32,57.00,40.71,55.13,43.16,32.26,39.65,...,35.75,51.59,43.57,42.13,11.09,68.61,52.25,68.00,24.11,41.13
1,59.99,10.08,40.91,33.31,57.71,40.36,54.57,43.77,32.18,39.62,...,35.74,51.63,43.59,42.22,11.06,68.86,52.24,67.87,24.01,40.81
2,59.66,10.23,41.71,33.34,57.18,40.59,54.54,43.60,32.06,39.71,...,35.60,51.84,43.67,42.39,11.09,68.63,52.31,68.02,24.09,41.37
3,59.38,10.22,41.81,33.33,57.42,40.06,55.39,43.45,31.99,39.73,...,35.61,51.34,43.78,42.55,11.07,68.01,52.24,67.76,24.12,40.83
4,59.21,10.20,42.12,33.31,57.10,40.15,55.26,43.17,32.01,39.87,...,35.75,51.84,43.79,42.18,11.14,67.09,52.22,67.74,24.05,40.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,63.29,9.96,41.77,32.15,57.24,47.76,49.90,36.99,33.08,35.28,...,34.29,51.09,42.10,41.21,9.03,50.03,52.44,63.56,20.63,43.02
246,63.74,9.95,41.70,32.10,57.52,47.97,49.96,37.13,32.93,35.15,...,34.37,50.69,42.07,40.83,9.01,48.97,52.44,63.56,20.58,43.03
247,63.44,9.90,41.88,32.08,57.67,48.10,49.79,37.35,32.99,35.15,...,34.41,51.01,42.15,40.95,9.00,48.67,52.40,63.55,20.52,43.57
248,63.18,9.84,42.40,32.07,57.55,48.98,49.54,38.05,33.08,35.13,...,34.44,50.84,42.08,40.48,8.96,48.06,52.53,64.20,20.54,43.13
249,63.32,9.83,42.25,32.05,57.74,48.34,48.50,38.40,33.11,35.04,...,34.41,51.03,42.12,40.72,9.00,47.70,52.53,64.29,20.56,43.33

In [5]:
# create data

closePrice = []
for stock in range(50):
    closePrice.extend(prcAll[stock])

dates = []
for stock in range(50):
    for day in range(250):
        dates.append(day)

stocks = []

for stock in range(50):
    stocks.extend([stock]*250)


full_data = pd.DataFrame({'date': dates, 'stock': stocks, 'closePrice': closePrice})

In [6]:
full_data.to_csv('../data/basic_data.csv', index=False)